# Conda Environment Configuration for Data Pipeline
name: iheardai-data-pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.11
  
  # Data Processing
  - pandas=2.1.*
  - numpy=1.24.*
  - pyarrow=13.*
  - polars=0.19.*
  
  # Database Drivers
  - psycopg2=2.9.*
  - redis-py=5.0.*
  - sqlalchemy=2.0.*
  - alembic=1.12.*
  
  # Kafka
  - confluent-kafka=2.2.*
  - kafka-python=2.0.*
  
  # HTTP and API clients
  - requests=2.31.*
  - httpx=0.25.*
  - aiohttp=3.8.*
  
  # Async/Concurrent Processing
  - asyncio
  - asyncpg=0.28.*
  - aioredis=2.0.*
  
  # Configuration Management
  - pydantic=2.4.*
  - pydantic-settings=2.0.*
  - python-dotenv=1.0.*
  - pyyaml=6.0.*
  
  # Cloud SDKs
  - boto3=1.28.*  # S3-compatible Spaces
  - botocore=1.31.*
  
  # Monitoring and Observability
  - prometheus-client=0.17.*
  - structlog=23.1.*
  - sentry-sdk=1.32.*
  
  # Data Validation
  - marshmallow=3.20.*
  - cerberus=1.3.*
  - jsonschema=4.19.*
  
  # Utilities
  - click=8.1.*
  - rich=13.5.*
  - tabulate=0.9.*
  - tqdm=4.66.*
  
  # Testing
  - pytest=7.4.*
  - pytest-asyncio=0.21.*
  - pytest-cov=4.1.*
  - pytest-mock=3.11.*
  - fakeredis=2.18.*
  
  # Development Tools
  - black=23.7.*
  - flake8=6.0.*
  - mypy=1.5.*
  - pre-commit=3.4.*
  
  # Jupyter (for data exploration)
  - jupyter=1.0.*
  - ipykernel=6.25.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  
  # Additional pip packages
  - pip
  - pip:
    - marketo-rest-python==1.0.1
    - digital-ocean-spaces==1.2.0
    - kafka-python-ng==2.2.0
    - redis-om==0.2.1
    - asyncio-mqtt==0.13.0
    - fastapi==0.103.1
    - uvicorn[standard]==0.23.2
    - kubernetes==27.2.0
    - prometheus-fastapi-instrumentator==6.1.0
    - opentelemetry-api==1.20.0
    - opentelemetry-sdk==1.20.0
    - opentelemetry-instrumentation==0.41b0